# Generated by Django 4.1.6 on 2023-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0003_alter_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_associe_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[(1, 'django'), (2, 'manu21'), (3, 'manu30'), (4, 'manu33'), (5, 'manu63'), (6, 'zaza')], max_length=10)),
            ],
        ),
    ]
