# Generated by Django 4.1.6 on 2023-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0004_notes_associe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9 h', '9h'), ('9h55', '9h55'), ('10h50', '10h50'), ('11h45', '11h45'), ('13h30', '13h30'), ('14h25', '14h25'), ('15h20', '15h20'), ('16h15', '16h15')], default='3 PM', max_length=10),
        ),
    ]
