# Generated by Django 4.1.6 on 2023-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0007_rename_user_note_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_associe_user',
            name='nom',
            field=models.CharField(max_length=10),
        ),
    ]
