# Generated by Django 4.1.6 on 2023-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0008_alter_notes_associe_user_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_associe_user',
            name='nom',
            field=models.CharField(choices=[('django', 'django'), ('manu21', 'manu21'), ('manu30', 'manu30'), ('manu33', 'manu33'), ('manu63', 'manu63'), ('zaza', 'zaza')], max_length=10),
        ),
    ]
